import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BiCopyright } from 'react-icons/bi'
import Navbar from '../components/Navbar/navbar'
import styled from 'styled-components'
import Hero from '../components/Hero/hero'
import { Cards } from '../components/Cards/cards'
import { Works } from '../components/Work/work'
import { Education } from '../components/Education/education'
import { Contact } from '../components/Contact/contact'

const Title = styled.h1`
  font-size: 80px;
  text-align: center;
  text-decoration: underline;
  text-decoration-thickness: 12px;
  text-decoration-color: #FA387F;
  margin-top: 1.25em;
  cursor: default;

  @media only screen and (max-width: 1000px) {
    font-size: 40px;
    text-decoration-thickness: 6px;
  }
`

const Footer = styled.footer`
  text-align: center;
  font-size: 13px;
  padding: 2em;
  background-color: #272727;
  color: #FA387F;
  font-weight: 600;
  margin-top: 1.5em;
  cursor: default;
`

const Container = styled.div`
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
`

export default function Home() {
  return (
    <div className={styles.container}>
    <Navbar />
      <Head>
        <title>Algren Pauna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jake.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <Hero />

        <Title className="projects">Projects</Title>
        <Container>
          <Cards
            img="/zzz-tracker.JPG"
            title="Zzz-Tracker"
            description="A Daily Sleep Tracker webapp created with React, TailwindCSS and JavaScript. For it's backend, it uses Firebase Authentication and Firestore for the database. It also features React-Vis to create a graph based on the user's entries."
            live="https://zzz-tracker.herokuapp.com/"
            github="https://github.com/algren123/zzz-tracker"
          />
          <Cards
            img="/top-spotify-stats.JPG"
            title="Top Spotify Stats"
            description="A website that uses Spotify's API to display some the user's listening statistics, such as top artists or songs of the week/month/all time. It uses Angular, TypeScript and TailwindCSS"
            live="https://top-spotify-stats.herokuapp.com/"
            github="https://github.com/algren123/top-spotify-stats"
            />
          <Cards
            img="/gulag-bot.JPG"
            title="Gulag Bot"
            description="A Discord bot created in Node.JS. I created it for my own server where I spend time with my friends. It features moderation and can also play music from YouTube"
            live="https://discord.com/oauth2/authorize?client_id=858052116751974420&scope=bot"
            github="https://github.com/algren123/gulag-bot"
            />
          <Cards
            img="/odeko-replica.JPG"
            title="Odeko Replica Website"
            description="A fully responsive website that is a recreation of Odeko's (now) old website. It is primarily frontend focused and was built with React, JavaScript and Material-UI"
            live="https://odeko-replica-react.netlify.app/"
            github="https://github.com/algren123/odeko-replica-website"
            />
        </Container>

        <Title className="work-experience">Work Experience</Title>
        <Container>
          <Works
            title="Junior Web Developer"
            company="Vertu Motors"
            duration="February 2021 - Present"
            description="Working with Angular, TypeScript, JavaScript and of course HTML, CSS & SASS to maintain Vertu Motor's 14 websites.
            I had the opportunities to work on various different parts of software development, from fixing bugs on the websites, to creating a chatbot"
          />
          <Works
            title="Code Hero Volunteer"
            company="Cartea Daliei"
            duration="March 2021 - Present"
            description="Cartea Daliei is a non-profit organization that works with children from Romania. I teach a class of 4 children aged between 11-12 the fundamentals of coding with Scratch.
            After 6 weeks of lessons, I have prepared them for a Hackathon-type project where they got to work together as a team and create an animation."
          />
        </Container>

        <Title className="education">Education</Title>
        <Education
          course="BSc Visual Effects (VFX)"
          university="De Montfort University"
          duration="October 2017 - July 2020"
          description="I had the chance to work with some industry titans where I learnt the importance that the attention to detail has and what a good design foundation is.
          The VFX industry was not a right fit for me, which motivated me to self-teach coding. The material and lectures were eye-opening and they still impact the way I work in my daily web dev work."
        />
        <Title className="contact">Contact me!</Title>
        <Contact />
      </main>

      <Footer>
          Copyright 2021 Algren Pauna. All rights reserved.
      </Footer>
    </div>
  )
}
